version: "3.8"
services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fluxo-net

  task-service:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env 
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: ${MYSQL_PORT}
      DB_NAME: ${MYSQL_DB}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - fluxo-net

volumes:
  mysql_data:

networks:
  fluxo-net:
    driver: bridge
